spring:
  application:
    name: Mobble-Server

  config:
    import: optional:file:.env[.properties]

  messages:
    basename: validationMessages, globalMessages
    encoding: UTF-8

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

        jwt:
          secret: 'eignindiglriljiljlisjt9a3jigasjbxzvjnnm,bzxbmpowiataweqwqqpoigkroeperjtklf953tjoi09v028hbsd'
          access-token-validity-in-seconds: 3600 # 1hour
          refresh-token-validity-in-seconds: 259200 # 7days